import { saveDocument } from '../lib/firebase';
import { WorkOrder } from '../types';
import { get21Diagnostics } from './diagnosticUtils';

export const generate10TestTickets = (): WorkOrder[] => {
  const now = Date.now();
  const dayMs = 86400000;

  const tickets: WorkOrder[] = [
    // 1. WO-2026-0001: Receive status - Pre-Diag Pending (Unchecked initial 21-point check)
    {
      id: "seed-ticket-1",
      orderNumber: "WO-2026-0001",
      customerId: "cust-1",
      customerName: "Aung Aung",
      customerPhone: "09971234567",
      customerEmail: "aungaung@example.com",
      customerAddress: "Kamayut Township, Yangon",
      customerType: "Retail",
      deviceCategory: "iPhone",
      deviceModel: "iPhone 16 Pro Max",
      serialNumber: "XN82937401",
      imei: "358912345678901",
      deviceColor: "Desert Titanium",
      passcode: "123456",
      findMyStatus: "OFF",
      status: "Receive",
      priority: "Urgent",
      assignedTechId: "tech-1",
      assignedTechName: "Aung Ko Ko",
      serviceType: "Standard Modular",
      intakeChecklist: {
        powerOn: true,
        screenDisplay: true,
        touchGrid: true,
        faceIdOrTouchId: true,
        trueTonePresent: true,
        frontCamera: true,
        rearCamera: true,
        microphones: true,
        speakers: true,
        wifiBluetooth: true,
        cellularSignal: true,
        wirelessCharging: true,
        liquidIndicatorTriggered: false,
        batteryHealthPercent: 84,
        physicalDamageNotes: "Cracked back glass and weak battery"
      },
      symptomsReported: "Battery drains very fast. Back glass shattered.",
      beforeDiagnostics: [], // Intentionally empty to test Pre-Diag Alert (! icon)
      afterDiagnostics: [],
      lineItems: [
        { id: 'li-1-1', description: 'iPhone 16 Pro Max Battery Replacement', unitCost: 45000, unitPrice: 85000, quantity: 1, isLabor: false },
        { id: 'li-1-2', description: 'iPhone 16 Pro Max Back Glass (Desert Titanium)', unitCost: 35000, unitPrice: 75000, quantity: 1, isLabor: false },
        { id: 'li-1-3', description: 'Labor: Modular Installation', unitCost: 0, unitPrice: 40000, quantity: 1, isLabor: true }
      ],
      subtotal: 200000,
      depositAmount: 50000,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount: 200000,
      isPaid: false,
      warrantyDays: 90,
      warrantyLabel: "90 Days Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 0.2).toISOString(),
      updatedAt: new Date(now - dayMs * 0.2).toISOString(),
      estimatedCompletion: new Date(now + dayMs * 1).toISOString(),
    },

    // 2. WO-2026-0002: Receive status - Pre-Diag Completed & Passed
    {
      id: "seed-ticket-2",
      orderNumber: "WO-2026-0002",
      customerId: "cust-2",
      customerName: "Daw Su Su",
      customerPhone: "09771112223",
      customerEmail: "susu@example.com",
      customerAddress: "Bahan Township, Yangon",
      customerType: "Retail",
      deviceCategory: "iPad",
      deviceModel: "iPad Air (5th Gen)",
      serialNumber: "DLXQ912345",
      deviceColor: "Space Gray",
      passcode: "000000",
      findMyStatus: "ON",
      status: "Receive",
      priority: "Normal",
      assignedTechId: "tech-2",
      assignedTechName: "Kyaw Swar Lin",
      serviceType: "Standard Modular",
      intakeChecklist: {
        powerOn: true,
        screenDisplay: true,
        touchGrid: false,
        faceIdOrTouchId: true,
        trueTonePresent: true,
        frontCamera: true,
        rearCamera: true,
        microphones: true,
        speakers: true,
        wifiBluetooth: true,
        cellularSignal: false,
        wirelessCharging: false,
        liquidIndicatorTriggered: false,
        physicalDamageNotes: "Glass digitizer unresponsive in center zone"
      },
      symptomsReported: "Touch screen not working in the middle.",
      beforeDiagnostics: get21Diagnostics(
        [
          { id: 'd1', name: '3. Touch Screen Digitizer Grid Response', status: 'Fail', note: 'Center zone dead' },
          { id: 'd2', name: '1. Power On & Boot State Logic', status: 'Pass', note: 'Boots cleanly' }
        ],
        "Touch screen not working in the middle"
      ),
      afterDiagnostics: [],
      lineItems: [
        { id: 'li-2-1', description: 'iPad Air 5 Front Glass Touch Digitizer', unitCost: 65000, unitPrice: 120000, quantity: 1, isLabor: false },
        { id: 'li-2-2', description: 'Labor: iPad Glass Separation & Lamination', unitCost: 0, unitPrice: 50000, quantity: 1, isLabor: true }
      ],
      subtotal: 170000,
      depositAmount: 30000,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount: 170000,
      isPaid: false,
      warrantyDays: 60,
      warrantyLabel: "60 Days Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 0.5).toISOString(),
      updatedAt: new Date(now - dayMs * 0.5).toISOString(),
      estimatedCompletion: new Date(now + dayMs * 2).toISOString(),
    },

    // 3. WO-2026-0003: In Progress status - Active Board Micro-Soldering
    {
      id: "seed-ticket-3",
      orderNumber: "WO-2026-0003",
      customerId: "cust-3",
      customerName: "U Kyaw Kyaw",
      customerPhone: "095012345",
      customerEmail: "kyawkyaw@example.com",
      customerAddress: "Kyauktada Township, Yangon",
      customerType: "B2B Corporate",
      deviceCategory: "MacBook",
      deviceModel: "MacBook Pro 16 (M3 Max)",
      serialNumber: "C02F391039",
      deviceColor: "Space Black",
      passcode: "password123",
      findMyStatus: "OFF",
      status: "In Progress",
      priority: "B2B Priority",
      assignedTechId: "tech-3",
      assignedTechName: "Thura Aung",
      serviceType: "Micro-Soldering",
      intakeChecklist: {
        powerOn: true,
        screenDisplay: true,
        touchGrid: true,
        faceIdOrTouchId: true,
        trueTonePresent: true,
        frontCamera: true,
        rearCamera: true,
        microphones: true,
        speakers: false,
        wifiBluetooth: true,
        cellularSignal: false,
        wirelessCharging: false,
        liquidIndicatorTriggered: true,
        batteryHealthPercent: 98,
        physicalDamageNotes: "Liquid ingress near Type-C audio codec IC"
      },
      symptomsReported: "Water spill on keyboard side. Audio speaker crackling & silent.",
      beforeDiagnostics: get21Diagnostics(
        [
          { id: 'd1', name: '9. Speakers & Audio DAC Output', status: 'Fail', note: 'No sound output' },
          { id: 'd2', name: '13. Liquid Ingress Contact Indicator (LCI)', status: 'Fail', note: 'Red LCI triggered' }
        ],
        "Water spill on keyboard side. Audio speaker crackling"
      ),
      afterDiagnostics: [],
      lineItems: [
        { id: 'li-3-1', description: 'MacBook Pro Audio Codec IC Chipset Replacement', unitCost: 30000, unitPrice: 150000, quantity: 1, isLabor: false },
        { id: 'li-3-2', description: 'Labor: Ultrasonic Board Cleaning & Micro-Soldering', unitCost: 0, unitPrice: 150000, quantity: 1, isLabor: true }
      ],
      subtotal: 300000,
      depositAmount: 100000,
      discountAmount: 20000,
      taxAmount: 0,
      totalAmount: 280000,
      isPaid: false,
      warrantyDays: 180,
      warrantyLabel: "180 Days Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 1.5).toISOString(),
      updatedAt: new Date(now - dayMs * 0.2).toISOString(),
      estimatedCompletion: new Date(now + dayMs * 2).toISOString(),
    },

    // 4. WO-2026-0004: Pending status - Waiting for Supplier Part Delivery
    {
      id: "seed-ticket-4",
      orderNumber: "WO-2026-0004",
      customerId: "cust-4",
      customerName: "Ma Mya Mya",
      customerPhone: "0995551234",
      customerEmail: "myamya@example.com",
      customerAddress: "Sanchaung Township, Yangon",
      customerType: "Retail",
      deviceCategory: "iPhone",
      deviceModel: "iPhone 13 Pro Max",
      serialNumber: "RF8W192837",
      imei: "354928172938102",
      deviceColor: "Titanium Gray",
      passcode: "2580",
      findMyStatus: "OFF",
      status: "Pending",
      priority: "Normal",
      assignedTechId: "tech-4",
      assignedTechName: "Min Htet (Senior Tech)",
      serviceType: "Standard Modular",
      intakeChecklist: {
        powerOn: true,
        screenDisplay: false,
        touchGrid: false,
        faceIdOrTouchId: true,
        trueTonePresent: true,
        frontCamera: true,
        rearCamera: true,
        microphones: true,
        speakers: true,
        wifiBluetooth: true,
        cellularSignal: true,
        wirelessCharging: true,
        liquidIndicatorTriggered: false,
        batteryHealthPercent: 95,
        physicalDamageNotes: "AMOLED screen destroyed"
      },
      symptomsReported: "Dropped on concrete. Screen completely black with green lines.",
      beforeDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '2. OLED / LCD Screen Display Panel', status: 'Fail', note: 'Black screen' }],
        "Screen completely black"
      ),
      afterDiagnostics: [],
      lineItems: [
        { id: 'li-4-1', description: 'Samsung Galaxy S24 Ultra Original Dynamic AMOLED Screen', unitCost: 180000, unitPrice: 280000, quantity: 1, isLabor: false },
        { id: 'li-4-2', description: 'Labor: Frame Seal & Heat Transfer', unitCost: 0, unitPrice: 40000, quantity: 1, isLabor: true }
      ],
      subtotal: 320000,
      depositAmount: 100000,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount: 320000,
      isPaid: false,
      warrantyDays: 90,
      warrantyLabel: "90 Days Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 2).toISOString(),
      updatedAt: new Date(now - dayMs * 0.1).toISOString(),
      estimatedCompletion: new Date(now + dayMs * 3).toISOString(),
    },

    // 5. WO-2026-0005: In Progress status - Repair Complete, Post-Diag QA Pending
    {
      id: "seed-ticket-5",
      orderNumber: "WO-2026-0005",
      customerId: "cust-5",
      customerName: "U Ko Ko",
      customerPhone: "09444112233",
      customerEmail: "koko@example.com",
      customerAddress: "Mayangone Township, Yangon",
      customerType: "Retail",
      deviceCategory: "AppleWatch",
      deviceModel: "Apple Watch Ultra 2",
      serialNumber: "GYXQ192837",
      deviceColor: "Titanium Case",
      passcode: "1122",
      findMyStatus: "OFF",
      status: "In Progress",
      priority: "Normal",
      assignedTechId: "tech-5",
      assignedTechName: "Zin Mar Win",
      serviceType: "Standard Modular",
      intakeChecklist: {
        powerOn: true,
        screenDisplay: true,
        touchGrid: true,
        faceIdOrTouchId: true,
        trueTonePresent: true,
        frontCamera: true,
        rearCamera: true,
        microphones: true,
        speakers: true,
        wifiBluetooth: true,
        cellularSignal: true,
        wirelessCharging: true,
        liquidIndicatorTriggered: false,
        batteryHealthPercent: 78,
        physicalDamageNotes: "Original battery swollen"
      },
      symptomsReported: "Battery swelling lifting watch display.",
      beforeDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '14. Battery Health & Charging Rate', status: 'Fail', note: 'Swollen battery 78%' }],
        "Battery swelling"
      ),
      afterDiagnostics: [], // Intentionally empty to test Post-Diag QA warning modal on move to Finished!
      lineItems: [
        { id: 'li-5-1', description: 'Apple Watch Ultra 2 OEM Battery Unit', unitCost: 35000, unitPrice: 75000, quantity: 1, isLabor: false },
        { id: 'li-5-2', description: 'Labor: Waterproof Gasket Renewal & Sealing', unitCost: 0, unitPrice: 35000, quantity: 1, isLabor: true }
      ],
      subtotal: 110000,
      depositAmount: 30000,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount: 110000,
      isPaid: false,
      warrantyDays: 90,
      warrantyLabel: "90 Days Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 1).toISOString(),
      updatedAt: new Date(now - dayMs * 0.1).toISOString(),
      estimatedCompletion: new Date(now + dayMs * 1).toISOString(),
    },

    // 6. WO-2026-0006: Finished status - Post-Repair QA Diag Passed & Ready for Checkout
    {
      id: "seed-ticket-6",
      orderNumber: "WO-2026-0006",
      customerId: "cust-6",
      customerName: "Daw Khin Aye",
      customerPhone: "09250001122",
      customerEmail: "khinaye@example.com",
      customerAddress: "Mandalay City",
      customerType: "Retail",
      deviceCategory: "iPhone",
      deviceModel: "iPhone 15 Pro",
      serialNumber: "F92KD01928",
      imei: "359012384910293",
      deviceColor: "Natural Titanium",
      passcode: "998877",
      findMyStatus: "OFF",
      status: "Finished",
      priority: "Urgent",
      assignedTechId: "tech-1",
      assignedTechName: "Aung Ko Ko",
      serviceType: "Standard Modular",
      intakeChecklist: {
        powerOn: true,
        screenDisplay: false,
        touchGrid: false,
        faceIdOrTouchId: true,
        trueTonePresent: true,
        frontCamera: true,
        rearCamera: true,
        microphones: true,
        speakers: true,
        wifiBluetooth: true,
        cellularSignal: true,
        wirelessCharging: true,
        liquidIndicatorTriggered: false,
        batteryHealthPercent: 88,
        physicalDamageNotes: "Shattered OLED screen"
      },
      symptomsReported: "Cracked screen from fall.",
      beforeDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '2. OLED / LCD Screen Display Panel', status: 'Fail', note: 'Cracked glass' }],
        "Cracked screen from fall"
      ),
      afterDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '2. OLED / LCD Screen Display Panel', status: 'Pass', note: 'New OEM Screen Tested OK' }],
        "Cracked screen"
      ).map((item) => ({ ...item, status: 'Pass' as const, note: 'QA Verified OK' })),
      lineItems: [
        { id: 'li-6-1', description: 'iPhone 15 Pro OEM Display Assembly', unitCost: 110000, unitPrice: 190000, quantity: 1, isLabor: false },
        { id: 'li-6-2', description: 'Labor: TrueTone Programming & Screen Mount', unitCost: 0, unitPrice: 40000, quantity: 1, isLabor: true }
      ],
      subtotal: 230000,
      depositAmount: 50000,
      discountAmount: 10000,
      taxAmount: 0,
      totalAmount: 220000,
      isPaid: false,
      warrantyDays: 180,
      warrantyLabel: "180 Days Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 2.5).toISOString(),
      updatedAt: new Date(now - dayMs * 0.3).toISOString(),
      estimatedCompletion: new Date(now - dayMs * 0.1).toISOString(),
    },

    // 7. WO-2026-0007: Finished status - Ready for POS Cashout
    {
      id: "seed-ticket-7",
      orderNumber: "WO-2026-0007",
      customerId: "cust-7",
      customerName: "Mg Htet Naing",
      customerPhone: "09780009988",
      customerEmail: "htetnaing@example.com",
      customerAddress: "Dagon Township, Yangon",
      customerType: "Retail",
      deviceCategory: "MacBook",
      deviceModel: "MacBook Air 15 (M2)",
      serialNumber: "C02G819201",
      deviceColor: "Starlight",
      passcode: "123123",
      findMyStatus: "OFF",
      status: "Finished",
      priority: "Normal",
      assignedTechId: "tech-3",
      assignedTechName: "Thura Aung",
      serviceType: "Standard Modular",
      intakeChecklist: {
        powerOn: true,
        screenDisplay: true,
        touchGrid: true,
        faceIdOrTouchId: true,
        trueTonePresent: true,
        frontCamera: true,
        rearCamera: true,
        microphones: true,
        speakers: true,
        wifiBluetooth: true,
        cellularSignal: false,
        wirelessCharging: false,
        liquidIndicatorTriggered: false,
        batteryHealthPercent: 91,
        physicalDamageNotes: "Keyboard sticky spacebar & enter key"
      },
      symptomsReported: "Keys sticking on top row after coffee splash.",
      beforeDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '10. Keyboard & Trackpad Mechanical Inputs', status: 'Fail', note: 'Sticky keys' }],
        "Keys sticking"
      ),
      afterDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '10. Keyboard & Trackpad Mechanical Inputs', status: 'Pass', note: 'New Keyboard Replaced & Tested' }],
        "Keys sticking"
      ).map((item) => ({ ...item, status: 'Pass' as const, note: 'All keys tactile & pass' })),
      lineItems: [
        { id: 'li-7-1', description: 'MacBook Air 15 M2 Original Keyboard Topcase Unit', unitCost: 120000, unitPrice: 220000, quantity: 1, isLabor: false },
        { id: 'li-7-2', description: 'Labor: Rivet Removal & Re-riveting Assembly', unitCost: 0, unitPrice: 80000, quantity: 1, isLabor: true }
      ],
      subtotal: 300000,
      depositAmount: 50000,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount: 300000,
      isPaid: false,
      warrantyDays: 90,
      warrantyLabel: "90 Days Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 3).toISOString(),
      updatedAt: new Date(now - dayMs * 0.5).toISOString(),
      estimatedCompletion: new Date(now - dayMs * 0.2).toISOString(),
    },

    // 8. WO-2026-0008: Taken Out status - Paid & Delivered to Customer
    {
      id: "seed-ticket-8",
      orderNumber: "WO-2026-0008",
      customerId: "cust-8",
      customerName: "Daw Nilar Win",
      customerPhone: "09960003344",
      customerEmail: "nilarwin@example.com",
      customerAddress: "Pyin Oo Lwin",
      customerType: "Retail",
      deviceCategory: "iPhone",
      deviceModel: "iPhone 14 Pro",
      serialNumber: "G09K192837",
      imei: "351029384756102",
      deviceColor: "Deep Purple",
      passcode: "111111",
      findMyStatus: "OFF",
      status: "Taken Out",
      priority: "Normal",
      assignedTechId: "tech-2",
      assignedTechName: "Kyaw Swar Lin",
      serviceType: "Standard Modular",
      intakeChecklist: {
        powerOn: true,
        screenDisplay: true,
        touchGrid: true,
        faceIdOrTouchId: true,
        trueTonePresent: true,
        frontCamera: true,
        rearCamera: true,
        microphones: true,
        speakers: true,
        wifiBluetooth: true,
        cellularSignal: true,
        wirelessCharging: true,
        liquidIndicatorTriggered: false,
        batteryHealthPercent: 82,
        physicalDamageNotes: "Charging port loose"
      },
      symptomsReported: "Charging cable drops connection when moved.",
      beforeDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '12. Lightning / USB-C Dock Port Connection', status: 'Fail', note: 'Intermittent charge' }],
        "Charging cable drops connection"
      ),
      afterDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '12. Lightning / USB-C Dock Port Connection', status: 'Pass', note: 'New Dock Flex Installed' }],
        "Charging cable drops"
      ).map((item) => ({ ...item, status: 'Pass' as const, note: 'Charging stable at 18W' })),
      lineItems: [
        { id: 'li-8-1', description: 'iPhone 14 Pro OEM USB-C/Dock Flex Cable', unitCost: 20000, unitPrice: 55000, quantity: 1, isLabor: false },
        { id: 'li-8-2', description: 'Labor: Modular Installation', unitCost: 0, unitPrice: 35000, quantity: 1, isLabor: true }
      ],
      subtotal: 90000,
      depositAmount: 90000,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount: 90000,
      isPaid: true,
      warrantyDays: 90,
      warrantyLabel: "90 Days Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 5).toISOString(),
      updatedAt: new Date(now - dayMs * 1).toISOString(),
      estimatedCompletion: new Date(now - dayMs * 2).toISOString(),
    },

    // 9. WO-2026-0009: Customer Not Repair status - Returned Unrepaired
    {
      id: "seed-ticket-9",
      orderNumber: "WO-2026-0009",
      customerId: "cust-9",
      customerName: "Mg Zaw Min",
      customerPhone: "09450007788",
      customerEmail: "zawmin@example.com",
      customerAddress: "Taunggyi",
      customerType: "Retail",
      deviceCategory: "iPhone",
      deviceModel: "iPhone 13 Mini",
      serialNumber: "F90LK19283",
      imei: "357102938475619",
      deviceColor: "Pink",
      passcode: "0000",
      findMyStatus: "OFF",
      status: "Customer Not Repair",
      priority: "Normal",
      assignedTechId: "tech-4",
      assignedTechName: "Min Htet (Senior Tech)",
      serviceType: "Micro-Soldering",
      intakeChecklist: {
        powerOn: false,
        screenDisplay: false,
        touchGrid: false,
        faceIdOrTouchId: false,
        trueTonePresent: false,
        frontCamera: false,
        rearCamera: false,
        microphones: false,
        speakers: false,
        wifiBluetooth: false,
        cellularSignal: false,
        wirelessCharging: false,
        liquidIndicatorTriggered: true,
        physicalDamageNotes: "Severe salt water corrosion on logic board"
      },
      symptomsReported: "Dropped into sea water during beach trip.",
      beforeDiagnostics: get21Diagnostics(
        [
          { id: 'd1', name: '1. Power On & Boot State Logic', status: 'Fail', note: 'Dead short on VDD_MAIN' },
          { id: 'd2', name: '13. Liquid Ingress Contact Indicator (LCI)', status: 'Fail', note: 'Corrosion throughout' }
        ],
        "Dropped into sea water"
      ),
      afterDiagnostics: [],
      lineItems: [],
      subtotal: 0,
      depositAmount: 0,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount: 0,
      isPaid: true,
      warrantyDays: 0,
      warrantyLabel: "No Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 4).toISOString(),
      updatedAt: new Date(now - dayMs * 2).toISOString(),
      estimatedCompletion: new Date(now - dayMs * 3).toISOString(),
    },

    // 10. WO-2026-0010: Cant Repair status - Unfixable BER Hardware Failure
    {
      id: "seed-ticket-10",
      orderNumber: "WO-2026-0010",
      customerId: "cust-10",
      customerName: "U Ba Thin",
      customerPhone: "09200005566",
      customerEmail: "bathin@example.com",
      customerAddress: "Naypyidaw",
      customerType: "Retail",
      deviceCategory: "iPhone",
      deviceModel: "iPhone 12 Pro Max",
      serialNumber: "PX8P1928301",
      imei: "351239840192834",
      deviceColor: "Bay Blue",
      passcode: "1234",
      findMyStatus: "OFF",
      status: "Cant Repair",
      priority: "Normal",
      assignedTechId: "tech-3",
      assignedTechName: "Thura Aung",
      serviceType: "Micro-Soldering",
      intakeChecklist: {
        powerOn: false,
        screenDisplay: false,
        touchGrid: false,
        faceIdOrTouchId: false,
        trueTonePresent: false,
        frontCamera: false,
        rearCamera: false,
        microphones: false,
        speakers: false,
        wifiBluetooth: false,
        cellularSignal: false,
        wirelessCharging: false,
        liquidIndicatorTriggered: false,
        physicalDamageNotes: "Board cracked across Tensor G3 SoC silicon layers"
      },
      symptomsReported: "Heavy impact runover. Infinite bootloop and heat spike.",
      beforeDiagnostics: get21Diagnostics(
        [{ id: 'd1', name: '1. Power On & Boot State Logic', status: 'Fail', note: 'Tensor G3 SoC cracked internally' }],
        "Infinite bootloop and heat spike"
      ),
      afterDiagnostics: [],
      lineItems: [
        { id: 'li-10-1', description: 'Diagnostic Service Fee (Board Delamination Check)', unitCost: 0, unitPrice: 15000, quantity: 1, isLabor: true }
      ],
      subtotal: 15000,
      depositAmount: 15000,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount: 15000,
      isPaid: true,
      warrantyDays: 0,
      warrantyLabel: "No Warranty",
      intakePhotos: [],
      createdAt: new Date(now - dayMs * 6).toISOString(),
      updatedAt: new Date(now - dayMs * 1.5).toISOString(),
      estimatedCompletion: new Date(now - dayMs * 2).toISOString(),
    }
  ];

  return tickets;
};

export const seedSampleTickets = async () => {
  const dummyTickets = generate10TestTickets();

  for (const t of dummyTickets) {
    try {
      await saveDocument('workOrders', t);
    } catch (e) {
      console.error("Failed to seed ticket: ", e);
    }
  }

  return dummyTickets;
};
